App Icon and Splash Screen
NJACKWinterOfCode/Android-ScorerApp pull request #16
Opened 2019-12-04 15:02 UTC by Sarthak2601

Fixes #12 and #14 

*Splash Screen added. 
*Handled splash through Manifest file. 
*App icon set to the app logo in drawables.

2019-12-04 18:07 UTC, chanmol1999 requested changes
Remove changes in .idea files and add a gif of the splash screen.

2019-12-05 04:05 UTC, Sarthak2601 commented
Removed changes in second commit. 
Added gif in the original PR.

2019-12-05 05:14 UTC, chanmol1999 requested changes

2019-12-05 05:14 UTC, chanmol1999 commented on Scorecounter/.idea/gradle.xml
> +        <option name="testRunner" value="PLATFORM" />
Can you remove this line.

2019-12-05 10:31 UTC, Sarthak2601 commented
Changes done.

2019-12-05 11:02 UTC, chanmol1999 commented
Resolve the merge conflicts.

2019-12-05 17:43 UTC, Sarthak2601 commented
@chanmol1999 I don't know why it is conflicting, the updated Gradle.xml file is exactly same as the original one. Please check.

2019-12-05 17:58 UTC, chanmol1999 commented
> @chanmol1999 I don't know why it is conflicting, the updated Gradle.xml file is exactly same as the original one. Please check.

Why don't you remove that file from your commit.
Just delete that file and push the changes.

2019-12-05 18:52 UTC, Sarthak2601 commented
@chanmol1999 Done.

2019-12-05 19:14 UTC, chanmol1999 approved these changes

2019-12-05 19:14 UTC, merged