conversion of string and dimen to resource form
NJACKWinterOfCode/Android-ScorerApp pull request #26
Opened 2019-12-06 20:19 UTC by adithya61

commit squashed
and .idea file changes not included.

2019-12-07 16:36 UTC, chanmol1999 requested changes

2019-12-07 16:36 UTC, chanmol1999 commented on Scorecounter/app/src/main/res/values/colors.xml
> -</resources>
Reason to remove this?

2019-12-07 16:36 UTC, chanmol1999 commented on Scorecounter/app/src/main/res/values/styles.xml
> -    </style>
Same why have you removed the styles?

2019-12-07 19:20 UTC, adithya61 commented on Scorecounter/app/src/main/res/values/colors.xml
> -</resources>
I don't remember removing this code.

2019-12-07 19:20 UTC, adithya61 commented on Scorecounter/app/src/main/res/values/styles.xml
> -    </style>
Even this one

2019-12-08 04:41 UTC, adithya61 commented
changes made

2019-12-08 11:10 UTC, chanmol1999 approved these changes

2019-12-08 11:10 UTC, merged