Football + Kabaddi + Bugs
NJACKWinterOfCode/Android-ScorerApp pull request #54
Opened 2019-12-13 22:06 UTC by Sarthak2601

Fixes #41  
Fixes #43 
Fixes #53 

**Bug Report -
Bug -- Canvas:trying to load too large bitmap 
Debugged the project and found that one image(Badminton image) in the UI was causing the app to crash again and again. 
Fix -- Changed the badminton image. App working properly now. 

**Football Counter 
New Improved UI 
Red and Yellow card functionality added along with usual reset and finish functions. 

**Kabaddi Counter 
New Improved UI 
New functionalities include - 
1. Bonus Point 
2. All Out 
3. Multi-Point scoring through dialog box. 
Along with usual reset and finish functions. 

**String file updated. 
The Main Activity UI contained hard coded data, so converted that to string resource. 
Kabaddi and Football counters also string resource coded. 

Attachments -- Kabaddi and Football Counters (gifs) 

![kab](https://user-images.githubusercontent.com/53938155/70835175-472bde00-1e22-11ea-8447-9d323493aadd.gif)
![kab2](https://user-images.githubusercontent.com/53938155/70835196-53b03680-1e22-11ea-9697-4ad8bdb06495.gif)

2019-12-13 22:06 UTC, Sarthak2601 commented
@chanmol1999 Kindly review and please ignore the gif quality. Thanks.

2019-12-14 05:34 UTC, chanmol1999 requested changes
Good work till now.
Just add a result summary in Football.
Like how many and which cards to each side etc.

2019-12-14 05:34 UTC, chanmol1999 commented on Scorecounter/app/src/main/res/layout/activity_main.xml
> +            android:layout_height="200sp"
Use resources for these dimensions.

2019-12-14 08:27 UTC, Sarthak2601 commented
@chanmol1999 
Updated the Alert Dialog box and the resources were used for dimensions. 
Screenshot Attached. 
![Screenshot_2019-12-14-13-52-15-898_com example anmol courtcounter](https://user-images.githubusercontent.com/53938155/70845851-889ba800-1e79-11ea-8b1f-f768d02da569.png)

2019-12-14 08:35 UTC, chanmol1999 approved these changes

2019-12-14 08:35 UTC, merged