Lawn Tennis scorer
NJACKWinterOfCode/Android-ScorerApp pull request #77
Opened 2019-12-25 14:24 UTC by Sarthak2601

Fixes #55 

-- Added Lawn Tennis icon in Main screen 
-- UI and Functionality of Lawn Tennis done. 

Attached GIF of functionality and Screenshot of result. 

PS - Implementing the logic of this game is a real challenge but equally fun. Thanks for the opportunity. 

![Screenrecorder-2019-12-25-19-29-29-314](https://user-images.githubusercontent.com/53938155/71447058-38152c00-2750-11ea-937f-640c1c029f80.gif)
![Screenshot_2019-12-25-19-31-21-427_com example anmol courtcounter](https://user-images.githubusercontent.com/53938155/71447060-3ea3a380-2750-11ea-88fe-a7604e59222a.png)

2019-12-25 14:52 UTC, Sarthak2601 commented
Resolved Conflicts in last commit.

2019-12-25 20:08 UTC, chanmol1999 requested changes

2019-12-25 20:08 UTC, chanmol1999 commented on Scorecounter/app/src/main/res/layout/activity_lawn_tennis.xml
> +                android:layout_marginTop="40dp"
Don't use hardcoded dimensions

2019-12-26 08:49 UTC, Sarthak2601 commented on Scorecounter/app/src/main/res/layout/activity_lawn_tennis.xml
> +                android:layout_marginTop="40dp"
@chanmol1999 Done.

2019-12-26 08:58 UTC, chanmol1999 approved these changes

2019-12-26 08:59 UTC, merged